### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by vincentmaule** [OptimisticShaggy/LAB-101-html-terminal-and-git#1]
## Host an extremely simple HTML file

@egillespie Can you take a look at this? It's [hosted here](https://OptimisticShaggy.github.io/LAB-101-html-terminal-and-git/index.html) and meets the following criteria:

- [x] A knock-knock joke is displayed when visiting the website
- [x] The code is pushed to GitHub
- [x] The website is hosted on GitHub Pages

**Comment by egillespie** [comment]
This looks great. To stretch you a little bit, would you mind using a list to show the parts of the joke?

After you’ve made your changes and pushed them to GitHub and your hosted site, give it a once-over to make sure it looks right, then comment back here and I’ll take another look.

Thanks! 🤘

**Comment by vincentmaule** [comment]
The stretch has been completed, thank you! :)

**Comment by egillespie** [comment]
You made quick work of that. Awesome job! 🎉 :shipit:

**Comment by vincentmaule** [comment]
Learned how to use Git and Github Pages. Especially love the feature of Github Pages.
